In [2]:
import numpy as np

In [3]:
lst = [1, 2, 3, 4, 5]
print(lst)

[1, 2, 3, 4, 5]


Advatnages of Numpy Array over Lists

In [11]:
print("1D Array")
a = np.array([1, 2, 3, 4, 5])
print(a)

#---------

print("2D Array")
b = np.array([[1, 2,3, 4, 5],
            [6, 7, 8, 9, 10]])
print(b)

#----------
print("3D Array")
c = np.array([[[1, 2, 3, 4, 5],
             [ 6, 7, 8, 9, 10],
             [11, 12, 13, 14, 15]]])
print(c)

1D Array
[1 2 3 4 5]
2D Array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
3D Array
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


In [12]:
type(a)

numpy.ndarray

size = Tells abput no. of elements in that array

In [16]:
print(a.size)
print(b.size)
print(c.size)

5
10
15


shape = (rows, cols)

In [18]:
print(a.shape)
print(b.shape)
print(c.shape)

(5,)
(2, 5)
(1, 3, 5)


dtype = Type of Data Present in the array

In [19]:
print(a.dtype)
print(b.dtype)
print(c.dtype)

int32
int32
int32


In [27]:
#Another datatype
d = np.array([[1, 2, 3, 4.2, 5],
              [6, 7, 8.9, 9, 10],
              [11, 12, 13, 14, 15]])
print(d.dtype)


float64


arr.transpose()

In [28]:
d.transpose()

array([[ 1. ,  6. , 11. ],
       [ 2. ,  7. , 12. ],
       [ 3. ,  8.9, 13. ],
       [ 4.2,  9. , 14. ],
       [ 5. , 10. , 15. ]])

np.empty((rows, cols), dtype)

In [32]:
np.empty((4,4),dtype = float)

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        6.23058707e-307],
       [2.22522597e-306, 1.33511969e-306, 1.37962320e-306,
        9.34604358e-307],
       [9.79101082e-307, 1.78020576e-306, 1.69119873e-306,
        2.22522868e-306],
       [1.24611809e-306, 8.06632139e-308, 1.60221208e-306,
        2.29178686e-312]])

np.ones((rows, cols), dtype)

In [38]:
x = np.ones(3)
x

array([1., 1., 1.])

In [40]:
y = np.ones((3,2))
y

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [41]:
x = np.ones((2,4), dtype = int)
print(x)

[[1 1 1 1]
 [1 1 1 1]]


In [47]:
x = np.ones((2,4), dtype = str)
print(x)

[['1' '1' '1' '1']
 ['1' '1' '1' '1']]


In [48]:
x = np.ones((2,4), dtype = bool)
print(x)

[[ True  True  True  True]
 [ True  True  True  True]]


# np.zeros((rows, cols), dtype)

In [43]:
x = np.zeros(4)
x

array([0., 0., 0., 0.])

In [44]:
y = np.zeros((2,3))
y

array([[0., 0., 0.],
       [0., 0., 0.]])

In [46]:
z = np.zeros((3,2), dtype = int)
z

array([[0, 0],
       [0, 0],
       [0, 0]])

In [49]:
x = np.zeros((2,4), dtype = str)
print(x)

[['' '' '' '']
 ['' '' '' '']]


In [50]:
x = np.zeros((2,4), dtype = bool)
print(x)

[[False False False False]
 [False False False False]]
